name: Build

on:
  push:
    branches:
      - master
      - jellyfin-ffmpeg

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Init vsDev for Windows
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Cache CMake build directory
        uses: actions/cache@v2
        with:
          path: build
          key: cmake-build-${{ runner.os }}
          restore-keys: |
            cmake-build-${{ runner.os }}-

      - name: CMake configure
        run: cmake -B build/native -G Ninja

      - name: CMake build
        run: cmake --build build/native --verbose

      - name: CMake package
        run: cmake --build build/native --target package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ScraperServer-${{ matrix.os }}-${{ runner.arch }}
          path: build/native/*.tar.gz